// <auto-generated />
using System;
using EcommerceWebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ecommerceWepApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EcommerceWebApi.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("EcommerceWebApi.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PriceAtTime")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItem");
                });

            modelBuilder.Entity("EcommerceWebApi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Fashion"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Home & Kitchen"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Beauty & Personal Care"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Health & Wellness"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Books & Stationery"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Toys & Baby Products"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Sports & Outdoors"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Groceries & Food"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Automotive"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Pet Supplies"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Jewelry & Watches"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            Name = "Gaming"
                        });
                });

            modelBuilder.Entity("EcommerceWebApi.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ShipToCity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ShipToCountry")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ShipToName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ShipToState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ShipToStreet")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ShipToZipCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("ShippingAddressId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ShippingAddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("EcommerceWebApi.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PriceAtPurchase")
                        .HasColumnType("numeric");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("EcommerceWebApi.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("EcommerceWebApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hydrates and soothes dry skin with natural ingredients.",
                            IsDeleted = false,
                            Name = "Aloe Vera Moisturizer",
                            Price = 42.99m,
                            StockQuantity = 54
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Accurate temperature readings in seconds.",
                            IsDeleted = false,
                            Name = "Digital Thermometer",
                            Price = 18.75m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Durable notebook for daily writing and notes.",
                            IsDeleted = false,
                            Name = "Hardcover Journal",
                            Price = 12.50m,
                            StockQuantity = 73
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Colorful blocks to teach kids letters and spelling.",
                            IsDeleted = false,
                            Name = "Educational Alphabet Blocks",
                            Price = 22.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Non-slip surface ideal for workouts and yoga sessions.",
                            IsDeleted = false,
                            Name = "Yoga Mat with Strap",
                            Price = 29.99m,
                            StockQuantity = 95
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Smooth spread made from roasted organic almonds.",
                            IsDeleted = false,
                            Name = "Organic Almond Butter",
                            Price = 8.99m,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hands-free phone use while driving.",
                            IsDeleted = false,
                            Name = "Car Phone Mount",
                            Price = 15.00m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Removes loose fur and detangles easily.",
                            IsDeleted = false,
                            Name = "Pet Grooming Brush",
                            Price = 10.99m,
                            StockQuantity = 88
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Elegant design suitable for daily wear or gifts.",
                            IsDeleted = false,
                            Name = "Silver Charm Bracelet",
                            Price = 35.00m,
                            StockQuantity = 33
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 13,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Compatible with major gaming consoles and PCs.",
                            IsDeleted = false,
                            Name = "Wireless Game Controller",
                            Price = 49.99m,
                            StockQuantity = 65
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Color-changing bulb controlled by app or voice.",
                            IsDeleted = false,
                            Name = "Smart LED Bulb",
                            Price = 17.95m,
                            StockQuantity = 110
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Stylish and stretchy denim for all-day comfort.",
                            IsDeleted = false,
                            Name = "Women's High-Waist Jeans",
                            Price = 44.50m,
                            StockQuantity = 75
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Complete set with ladle, spatula, and whisk.",
                            IsDeleted = false,
                            Name = "Stainless Steel Cooking Utensils",
                            Price = 26.30m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Removes impurities and refreshes skin.",
                            IsDeleted = false,
                            Name = "Charcoal Face Wash",
                            Price = 14.20m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Boosts immune system and skin health.",
                            IsDeleted = false,
                            Name = "Vitamin C Tablets",
                            Price = 9.50m,
                            StockQuantity = 130
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Organize your week with tear-off sheets.",
                            IsDeleted = false,
                            Name = "Planner & To-Do List Pad",
                            Price = 11.75m,
                            StockQuantity = 55
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Soft cotton for a cozy, snug fit.",
                            IsDeleted = false,
                            Name = "Baby Swaddle Blanket",
                            Price = 19.80m,
                            StockQuantity = 78
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Full-body workout bands with varying resistance.",
                            IsDeleted = false,
                            Name = "Resistance Bands Set",
                            Price = 23.99m,
                            StockQuantity = 49
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Freshly sealed for quality and aroma.",
                            IsDeleted = false,
                            Name = "Organic Green Tea Bags",
                            Price = 6.99m,
                            StockQuantity = 160
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Portable and powerful suction for quick cleanups.",
                            IsDeleted = false,
                            Name = "Car Vacuum Cleaner",
                            Price = 32.90m,
                            StockQuantity = 39
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Traps litter and keeps floors clean.",
                            IsDeleted = false,
                            Name = "Cat Litter Mat",
                            Price = 13.25m,
                            StockQuantity = 51
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Classic analog watch with genuine leather band.",
                            IsDeleted = false,
                            Name = "Men’s Leather Wristwatch",
                            Price = 59.00m,
                            StockQuantity = 29
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 13,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Customizable DPI and color profiles.",
                            IsDeleted = false,
                            Name = "Gaming Mouse with RGB Lighting",
                            Price = 27.49m,
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Slim design fits under TV with immersive sound.",
                            IsDeleted = false,
                            Name = "Bluetooth Soundbar",
                            Price = 89.99m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Casual wear with a smart collar and short sleeves.",
                            IsDeleted = false,
                            Name = "Men’s Polo Shirt",
                            Price = 34.75m,
                            StockQuantity = 66
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Durable pan perfect for everyday cooking needs.",
                            IsDeleted = false,
                            Name = "Non-Stick Frying Pan",
                            Price = 21.50m,
                            StockQuantity = 75
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Keeps lips soft and moisturized all day.",
                            IsDeleted = false,
                            Name = "Hydrating Lip Balm",
                            Price = 5.99m,
                            StockQuantity = 110
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Accurate home monitoring for your health.",
                            IsDeleted = false,
                            Name = "Digital Blood Pressure Monitor",
                            Price = 38.20m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Perfect for notes, journaling, or sketches.",
                            IsDeleted = false,
                            Name = "A5 Leather Notebook",
                            Price = 14.00m,
                            StockQuantity = 95
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Safe, colorful, and fun for your little one.",
                            IsDeleted = false,
                            Name = "Infant Rattle Toy Set",
                            Price = 18.45m,
                            StockQuantity = 62
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Great for muscle recovery and massage therapy.",
                            IsDeleted = false,
                            Name = "Foam Roller",
                            Price = 25.00m,
                            StockQuantity = 88
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-protein whole grain, perfect for salads.",
                            IsDeleted = false,
                            Name = "Organic Quinoa",
                            Price = 9.99m,
                            StockQuantity = 145
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Keeps your car cool and protects the interior.",
                            IsDeleted = false,
                            Name = "Windshield Sun Shade",
                            Price = 17.00m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tough and fun toy for chewing and playing.",
                            IsDeleted = false,
                            Name = "Dog Chew Toy",
                            Price = 11.75m,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A delicate piece for elegant outfits.",
                            IsDeleted = false,
                            Name = "Elegant Gold Necklace",
                            Price = 72.99m,
                            StockQuantity = 24
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 13,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Noise-canceling headset for immersive gameplay.",
                            IsDeleted = false,
                            Name = "Gaming Headset with Mic",
                            Price = 54.99m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Stabilizer for smooth mobile video recording.",
                            IsDeleted = false,
                            Name = "Smartphone Gimbal",
                            Price = 99.00m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lightweight and stylish for warm weather.",
                            IsDeleted = false,
                            Name = "Summer Maxi Dress",
                            Price = 45.50m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Stackable bowls with beautiful patterns.",
                            IsDeleted = false,
                            Name = "Ceramic Mixing Bowls Set",
                            Price = 34.99m,
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gently exfoliates and removes impurities.",
                            IsDeleted = false,
                            Name = "Facial Cleansing Brush",
                            Price = 29.90m,
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Monitors steps, heart rate, and sleep patterns.",
                            IsDeleted = false,
                            Name = "Fitness Tracker Watch",
                            Price = 59.00m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Assorted sizes and colors for quick reminders.",
                            IsDeleted = false,
                            Name = "Sticky Notes Combo Pack",
                            Price = 6.99m,
                            StockQuantity = 130
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Includes bibs, socks, and soft mittens.",
                            IsDeleted = false,
                            Name = "Newborn Gift Set",
                            Price = 22.00m,
                            StockQuantity = 43
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Stores phone and keys during workouts.",
                            IsDeleted = false,
                            Name = "Running Belt Pouch",
                            Price = 19.00m,
                            StockQuantity = 77
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Healthy and crunchy mix for on-the-go munching.",
                            IsDeleted = false,
                            Name = "Granola Snack Pack",
                            Price = 4.99m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Easy-to-read gauge for car safety.",
                            IsDeleted = false,
                            Name = "Tire Pressure Gauge",
                            Price = 12.99m,
                            StockQuantity = 85
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Non-slip and easy to clean.",
                            IsDeleted = false,
                            Name = "Pet Food Bowl Set",
                            Price = 16.99m,
                            StockQuantity = 65
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Timeless elegance for formal occasions.",
                            IsDeleted = false,
                            Name = "Classic Pearl Earrings",
                            Price = 39.50m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 13,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Responsive keys and customizable lighting.",
                            IsDeleted = false,
                            Name = "Gaming Keyboard with Backlight",
                            Price = 44.25m,
                            StockQuantity = 52
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Control devices remotely via app or voice assistant.",
                            IsDeleted = false,
                            Name = "Bluetooth Smart Plug",
                            Price = 23.75m,
                            StockQuantity = 68
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Breathable cotton polo for casual outings.",
                            IsDeleted = false,
                            Name = "Slim Fit Polo Shirt",
                            Price = 27.99m,
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Boils water quickly and shuts off automatically.",
                            IsDeleted = false,
                            Name = "Electric Kettle",
                            Price = 29.50m,
                            StockQuantity = 55
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Soothing and hydrating facial treatment.",
                            IsDeleted = false,
                            Name = "Aloe Vera Face Mask",
                            Price = 7.50m,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Non-slip and cushioned for floor workouts.",
                            IsDeleted = false,
                            Name = "Yoga Mat",
                            Price = 24.00m,
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Raw and nutritious snack for healthy living.",
                            IsDeleted = false,
                            Name = "Organic Almonds",
                            Price = 11.99m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Secure and adjustable phone holder for cars.",
                            IsDeleted = false,
                            Name = "Car Phone Mount",
                            Price = 13.75m,
                            StockQuantity = 85
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Protects furniture while entertaining your cat.",
                            IsDeleted = false,
                            Name = "Cat Scratching Post",
                            Price = 33.40m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Minimalist accessory with a timeless appeal.",
                            IsDeleted = false,
                            Name = "Silver Bracelet",
                            Price = 59.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 13,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Immersive virtual reality experience for gamers.",
                            IsDeleted = false,
                            Name = "VR Gaming Headset",
                            Price = 199.99m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fast-charging pad compatible with most smartphones.",
                            IsDeleted = false,
                            Name = "Wireless Charging Pad",
                            Price = 18.95m,
                            StockQuantity = 73
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lightweight and moisture-wicking for workouts.",
                            IsDeleted = false,
                            Name = "Men's Running Shorts",
                            Price = 22.50m,
                            StockQuantity = 65
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Set of 4 stylish mugs for your morning brew.",
                            IsDeleted = false,
                            Name = "Ceramic Coffee Mug Set",
                            Price = 17.00m,
                            StockQuantity = 92
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Brightens skin and improves texture.",
                            IsDeleted = false,
                            Name = "Vitamin C Serum",
                            Price = 21.99m,
                            StockQuantity = 105
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Deep cleaning and long battery life.",
                            IsDeleted = false,
                            Name = "Electric Toothbrush",
                            Price = 49.00m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Organize your day with to-do lists and schedules.",
                            IsDeleted = false,
                            Name = "Daily Planner Notebook",
                            Price = 12.99m,
                            StockQuantity = 110
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gentle care kit for your baby’s bath time.",
                            IsDeleted = false,
                            Name = "Baby Bath Essentials Set",
                            Price = 25.50m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Space-saving weights with adjustable settings.",
                            IsDeleted = false,
                            Name = "Adjustable Dumbbells",
                            Price = 129.99m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Delicious and fiber-rich alternative to white pasta.",
                            IsDeleted = false,
                            Name = "Whole Grain Pasta",
                            Price = 3.25m,
                            StockQuantity = 130
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Streak-free visibility in all weather.",
                            IsDeleted = false,
                            Name = "Windshield Wiper Blades",
                            Price = 15.00m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Reduces shedding and keeps coat shiny.",
                            IsDeleted = false,
                            Name = "Pet Grooming Brush",
                            Price = 9.99m,
                            StockQuantity = 98
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Elegant studs for everyday wear.",
                            IsDeleted = false,
                            Name = "Women's Stud Earrings",
                            Price = 28.50m,
                            StockQuantity = 55
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 13,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ergonomic and responsive buttons.",
                            IsDeleted = false,
                            Name = "Console Gaming Controller",
                            Price = 49.95m,
                            StockQuantity = 38
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "See and speak to visitors from your phone.",
                            IsDeleted = false,
                            Name = "Smart Doorbell Camera",
                            Price = 89.00m,
                            StockQuantity = 27
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Warm and stylish for cold days.",
                            IsDeleted = false,
                            Name = "Winter Beanie Hat",
                            Price = 14.99m,
                            StockQuantity = 66
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Non-stick mats perfect for healthy baking.",
                            IsDeleted = false,
                            Name = "Silicone Baking Mat Set",
                            Price = 19.50m,
                            StockQuantity = 74
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Deep cleans pores and controls oil.",
                            IsDeleted = false,
                            Name = "Charcoal Face Wash",
                            Price = 9.75m,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Easy-to-use monitor with accurate readings.",
                            IsDeleted = false,
                            Name = "Digital Blood Pressure Monitor",
                            Price = 45.99m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Classic journal for writing, sketching, or note-taking.",
                            IsDeleted = false,
                            Name = "Leather Journal",
                            Price = 17.25m,
                            StockQuantity = 95
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "BPA-free bottles for safe feeding.",
                            IsDeleted = false,
                            Name = "Baby Feeding Bottle Set",
                            Price = 28.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "5 levels for stretching, strength, or rehab.",
                            IsDeleted = false,
                            Name = "Resistance Bands Set",
                            Price = 21.50m,
                            StockQuantity = 85
                        },
                        new
                        {
                            Id = 84,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "100% raw and unfiltered natural honey.",
                            IsDeleted = false,
                            Name = "Organic Honey Jar",
                            Price = 13.99m,
                            StockQuantity = 105
                        },
                        new
                        {
                            Id = 85,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Compact and powerful vacuum for vehicles.",
                            IsDeleted = false,
                            Name = "Car Vacuum Cleaner",
                            Price = 39.00m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 86,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Durable toys to keep dogs entertained and healthy.",
                            IsDeleted = false,
                            Name = "Dog Chew Toy Pack",
                            Price = 18.00m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 87,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Elegant and simple chain for special occasions.",
                            IsDeleted = false,
                            Name = "Rose Gold Necklace",
                            Price = 69.50m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 88,
                            CategoryId = 13,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High precision and customizable lighting.",
                            IsDeleted = false,
                            Name = "Gaming Mouse with RGB",
                            Price = 32.75m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 89,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Wireless earbuds with noise isolation and mic.",
                            IsDeleted = false,
                            Name = "Bluetooth Earbuds",
                            Price = 44.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 90,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Classic blue denim with rugged stitching.",
                            IsDeleted = false,
                            Name = "Denim Jacket",
                            Price = 49.00m,
                            StockQuantity = 55
                        },
                        new
                        {
                            Id = 91,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Easy to clean and perfect for daily cooking.",
                            IsDeleted = false,
                            Name = "Non-stick Frying Pan",
                            Price = 25.50m,
                            StockQuantity = 65
                        },
                        new
                        {
                            Id = 92,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gently exfoliates and removes makeup.",
                            IsDeleted = false,
                            Name = "Facial Cleansing Brush",
                            Price = 14.99m,
                            StockQuantity = 95
                        },
                        new
                        {
                            Id = 93,
                            CategoryId = 5,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Boosts immunity and daily nutrition.",
                            IsDeleted = false,
                            Name = "Multivitamin Capsules",
                            Price = 19.95m,
                            StockQuantity = 140
                        },
                        new
                        {
                            Id = 94,
                            CategoryId = 6,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Perfect for desk organization.",
                            IsDeleted = false,
                            Name = "Planner Pad with Sticky Notes",
                            Price = 9.50m,
                            StockQuantity = 85
                        },
                        new
                        {
                            Id = 95,
                            CategoryId = 7,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Protects toddlers from dangerous drawers and cabinets.",
                            IsDeleted = false,
                            Name = "Baby Safety Locks",
                            Price = 12.99m,
                            StockQuantity = 77
                        },
                        new
                        {
                            Id = 96,
                            CategoryId = 8,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ideal for cardio and agility training.",
                            IsDeleted = false,
                            Name = "Jump Rope",
                            Price = 8.25m,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 97,
                            CategoryId = 9,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Nutritious and versatile superfood.",
                            IsDeleted = false,
                            Name = "Quinoa Grain Pack",
                            Price = 6.75m,
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 98,
                            CategoryId = 10,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Keeps car interior clean and items accessible.",
                            IsDeleted = false,
                            Name = "Car Organizer",
                            Price = 22.00m,
                            StockQuantity = 68
                        },
                        new
                        {
                            Id = 99,
                            CategoryId = 11,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Encourages pets to drink more water.",
                            IsDeleted = false,
                            Name = "Pet Water Fountain",
                            Price = 35.00m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 100,
                            CategoryId = 12,
                            CreatedAt = new DateTime(2025, 7, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Timeless design with water resistance.",
                            IsDeleted = false,
                            Name = "Luxury Watch",
                            Price = 199.00m,
                            StockQuantity = 25
                        });
                });

            modelBuilder.Entity("EcommerceWebApi.Models.ShippingAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ShippingAddress");
                });

            modelBuilder.Entity("EcommerceWebApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EcommerceWebApi.Models.Cart", b =>
                {
                    b.HasOne("EcommerceWebApi.Models.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcommerceWebApi.Models.CartItem", b =>
                {
                    b.HasOne("EcommerceWebApi.Models.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcommerceWebApi.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EcommerceWebApi.Models.Order", b =>
                {
                    b.HasOne("EcommerceWebApi.Models.ShippingAddress", "ShippingAddress")
                        .WithMany()
                        .HasForeignKey("ShippingAddressId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EcommerceWebApi.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ShippingAddress");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcommerceWebApi.Models.OrderItem", b =>
                {
                    b.HasOne("EcommerceWebApi.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcommerceWebApi.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EcommerceWebApi.Models.Payment", b =>
                {
                    b.HasOne("EcommerceWebApi.Models.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("EcommerceWebApi.Models.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("EcommerceWebApi.Models.Product", b =>
                {
                    b.HasOne("EcommerceWebApi.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EcommerceWebApi.Models.ShippingAddress", b =>
                {
                    b.HasOne("EcommerceWebApi.Models.User", "User")
                        .WithMany("ShippingAddresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EcommerceWebApi.Models.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("EcommerceWebApi.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("EcommerceWebApi.Models.Order", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payment")
                        .IsRequired();
                });

            modelBuilder.Entity("EcommerceWebApi.Models.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("EcommerceWebApi.Models.User", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Orders");

                    b.Navigation("ShippingAddresses");
                });
#pragma warning restore 612, 618
        }
    }
}
